---
title: "RI Bisection Analysis"
author: "Carter Daniels"
date: "2023-07-23"
output: html_document
---

```{r}
rm(list=ls())
#import libraries
library(tidyverse)
library(lme4)
library(stats)
library(shinystan)
library(cmdstanr)

#functions
min_na <- function(x)min(x,na.rm=T)

```

# 1. Temporal Bisection


```{r}

#datapath and functions

data.path <- "D:\\Dropbox Drive Folder\\Dropbox\\2 All of Carter's Stuff\\Carter Local\\JEAB_Habit_EricCollab\\"

```

```{r}


tbt_matrices <- readxl::read_excel(paste0(data.path,"testData_Romero_etal_paper.xlsx"))
tau <- apply(tbt_matrices,2,min_na)
tbt_matrices<-t(t(tbt_matrices) - tau)
tbt_matrices<-as.data.frame(tbt_matrices[c(1:1000),])
tbt_long <- pivot_longer(tbt_matrices,cols = c(Subj1:Subj11))
colnames(tbt_long)<-c("SubjectID","IRT")
tbt_long$SubjectID <-as.numeric(gsub("Subj","",tbt_long$SubjectID))
tbt_long <- tbt_long[complete.cases(tbt_long),]

```



```{r}

# for custom mixture: https://vasishth.github.io/bayescogsci/book/ch-mixture.html

biexp_stan <- "

// stan code for biexponential

data {

 int<lower=1> Nr; // number of data points
 int<lower=1> Ns; // number of subjects
 vector<lower=0>[Nr] y; //irts
 int s[Nr]; //subjects
 

}

parameters {

//parameters
real beta_short_mu;
real delta_long_mu; 
real L_mu;

vector[Ns] short_rme;
vector[Ns] long_rme;
vector[Ns] L_rme;

; 



}

transformed parameters {
vector[Nr] beta_short_temp;
vector[Nr] delta_long_temp;
vector[Nr] L_temp;

vector<lower=0>[Nr] beta_short;
vector<lower=0>[Nr] delta_long; 
vector<lower=0>[Nr] beta_long;
vector<lower=0>[Nr] L;
vector<lower=0,upper=1>[Nr] Q; 


for (i in 1:Nr)
{
  beta_short_temp[i] = short_rme[s[i]];
  delta_long_temp[i] = long_rme[s[i]];
  L_temp[i] = L_rme[s[i]]; 
  
}

  beta_short = exp(beta_short_temp+beta_short_mu); 
  delta_long = exp(delta_long_temp+delta_long_mu);
  L = exp(L_temp+L_mu);
  
  beta_long = beta_short + delta_long; 
  Q = exp(L)./(1+exp(L));

}

model {

//priors
//mean
target+= normal_lpdf(beta_short_mu|0.3,0.2);
target+= normal_lpdf(delta_long_mu|2,1.5);
target+= normal_lpdf(L_mu|5,4);


//subject specific shift from mean
target+= normal_lpdf(short_rme|0,0.2);
target+= normal_lpdf(long_rme|0,1.5);
target+= normal_lpdf(L_rme|0,4); 




//likelihood

for (i in 1:Nr)
{
  target+= log_sum_exp(log1m(Q[i])+exponential_lpdf(y[i]|beta_short[i]),log(Q[i])+exponential_lpdf(y[i]|beta_long[i])); //biexponential likelihood
}


}

"

write_stan_file(biexp_stan,
                dir=data.path,
                basename="biexp_stan",
                force_overwrite = TRUE)

#construct predictor matrix
# pred_matrix <- model.matrix(Choice~-1+InitiationType*AltCondition*IntervalCond, 
#                             data=tbt_matrices_TB)

# 
data_list <- list(Nr = nrow(tbt_long),
                  Ns = length(unique(tbt_long$SubjectID)),
                  y=tbt_long$IRT,
                  s=tbt_long$SubjectID)



#compile model
mod <- cmdstan_model(stan_file=file.path(paste0(data.path,
                                                "biexp_stan.stan")))
```


```{r}

fit <- mod$sample(data=data_list,
                  seed=123,
                  chains=1,
                  refresh=1,
                  num_samples=500,
                  num_warmup=500,
                  adapt_delta=0.99,
                  max_treedepth=30)


```


